name: Deploy Spring Boot Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file Airline_Service/service/pom.xml -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build Airline_Service -t junayed954/airline-service:latest

    - name: Push Docker image
      run: docker push junayed954/airline-service:latest

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f Airline_Service/docker-compose.yml down
        docker-compose -f Airline_Service/docker-compose.yml up -d

